# Generated by Django 5.0.2 on 2024-02-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('SP', 'SÃO PAULO'), ('PI', 'PIAUÍ'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('MT', 'MATO GROSSO'), ('MA', 'MARANHÃO'), ('SC', 'SANTA CATARINA'), ('RJ', 'RIO DE JANEIRO'), ('AM', 'AMAZONAS'), ('RN', 'RIO GRANDE DO NORTE')], max_length=32)),
                ('cores', models.CharField(max_length=40)),
                ('ano_de_fundação', models.PositiveIntegerField(default=1970, verbose_name='Ano de Fundação')),
                ('mundial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
    ]
